# Grid Searching Models



In [15]:
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV


In [21]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.neighbors import KNeighborsClassifier

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [3]:
np.linspace(0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [4]:
np.logspace(0, 1, 4)

array([ 1.        ,  2.15443469,  4.64158883, 10.        ])

In [ ]:
def full_fit(model, hyperparameters):
    pipe(scaling, heres the model)
    grid(hyperparameters)
    return(whatever you want it to return)

In [16]:
# Create a pipeline
# pipe = make_pipeline(StandardScaler(), )
grid = [{'n_neighbors': [2, 4]}]


pipe = Pipeline([('classifier', LinearRegression())])

# Create space of candidate learning algorithms and their hyperparameters
search_space = [{'classifier': [LogisticRegression()],
                 'classifier__penalty': ['l1', 'l2'],
                 'classifier__C': np.logspace(0, 4, 10)},
                {'classifier': [RandomForestClassifier()],
                 'classifier__n_estimators': [10, 100, 1000],
                 'classifier__max_features': [1, 2, 3]}]

In [17]:
clf = GridSearchCV(pipe, search_space, cv=5, verbose=0)

In [18]:
best_model = clf.fit(X, y)

In [20]:
best_model.get_params()


{'cv': 5,
 'error_score': 'raise',
 'estimator__memory': None,
 'estimator__steps': [('classifier',
   LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False))],
 'estimator__classifier': LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False),
 'estimator__classifier__copy_X': True,
 'estimator__classifier__fit_intercept': True,
 'estimator__classifier__n_jobs': 1,
 'estimator__classifier__normalize': False,
 'estimator': Pipeline(memory=None,
      steps=[('classifier', LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False))]),
 'fit_params': None,
 'iid': True,
 'n_jobs': 1,
 'param_grid': [{'classifier': [LogisticRegression(C=10000.0, class_weight=None, dual=False,
              fit_intercept=True, intercept_scaling=1, max_iter=100,
              multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
              solver='liblinear', tol=0.0001, verbose=0, warm_start=False)],
   'classifier__penalty': ['l1', 'l2

In [14]:
best_model.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Exercise

Using either a manual search or automated example like above, please examine the `ames_housing.csv` file, select appropriate features, perform necessary preprocessing, and compare the results of the following models:

- `LinearRegression`
- `Ridge`
- `Lasso`
- `DecisionTreeRegressor`
- `RandomForestRegressor`

You may want to incorporate a feature selection routine here.  Additionally, try bagging and boosting with two of the models to see if this improves performance. You can also compare the performance of the `xgboost` library.

- (10 minutes Preprocessing)
- (10 minutes Feature Selection)
- (10 minutes Model Implementation)
- (5 minutes evaluation and discussion)